import React from 'react';
import { X, Download, FileText, Image as ImageIcon } from 'lucide-react';
import { Button } from './UI';

interface DocumentViewerModalProps {
  isOpen: boolean;
  onClose: () => void;
  document: { name: string; type: 'pdf' | 'image' | 'contract' } | null;
}

export const DocumentViewerModal = ({ isOpen, onClose, document: doc }: DocumentViewerModalProps) => {
  if (!isOpen || !doc) return null;

  const handleDownload = () => {
    // Simulated Download Logic
    const element = document.createElement("a");
    const fileContent = `This is a mock content for file: ${doc.name}\n\nGenerated by TikTok Seeding OS.`;
    const file = new Blob([fileContent], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = doc.name;
    document.body.appendChild(element); // Required for this to work in FireFox
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="fixed inset-0 bg-gray-900/60 backdrop-blur-sm z-[70] flex items-center justify-center p-4 animate-in fade-in duration-200">
      <div className="bg-white rounded-2xl w-full max-w-3xl h-[80vh] flex flex-col shadow-2xl ring-1 ring-white/20">
        
        {/* Header */}
        <div className="px-6 py-4 border-b border-gray-100 flex justify-between items-center bg-gray-50 rounded-t-2xl">
           <div className="flex items-center gap-3">
              <div className="p-2 bg-white border border-gray-200 rounded-lg shadow-sm text-gray-700">
                 {doc.type === 'image' ? <ImageIcon size={20} /> : <FileText size={20} />}
              </div>
              <div>
                 <h2 className="text-base font-bold text-gray-900">{doc.name}</h2>
                 <p className="text-xs text-gray-500">Preview Mode</p>
              </div>
           </div>
           <div className="flex items-center gap-2">
              <Button variant="secondary" icon={Download} className="text-xs h-8" onClick={handleDownload}>Download</Button>
              <button onClick={onClose} className="p-2 hover:bg-gray-200 rounded-full text-gray-500 transition-colors">
                <X size={20} />
              </button>
           </div>
        </div>
        
        {/* Viewer Content */}
        <div className="flex-1 bg-gray-100 flex items-center justify-center p-8 overflow-hidden relative">
           {/* Background Pattern */}
           <div className="absolute inset-0 opacity-5" style={{ backgroundImage: 'radial-gradient(#64748b 1px, transparent 1px)', backgroundSize: '24px 24px' }}></div>
           
           <div className="bg-white shadow-xl rounded-xl w-full max-w-xl aspect-[3/4] flex flex-col items-center justify-center p-12 text-center border border-gray-200 z-10">
               {doc.type === 'image' ? (
                   <div className="space-y-4">
                       <div className="w-full h-48 bg-gray-50 rounded-lg flex items-center justify-center border-2 border-dashed border-gray-200">
                           <ImageIcon size={48} className="text-gray-300" />
                       </div>
                       <p className="text-sm text-gray-500">Image Preview Placeholder</p>
                       <p className="text-xs text-gray-400 font-mono">{doc.name}</p>
                   </div>
               ) : (
                   <div className="space-y-4">
                       <div className="w-24 h-32 bg-red-50 rounded-lg border border-red-100 flex items-center justify-center mx-auto">
                           <FileText size={48} className="text-red-400" />
                       </div>
                       <h3 className="text-lg font-bold text-gray-900">Document Preview</h3>
                       <p className="text-sm text-gray-500 max-w-xs mx-auto">
                           This is a simulated preview for the mock file. In a real environment, the PDF or Image blob would be rendered here.
                       </p>
                   </div>
               )}
           </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-3 border-t border-gray-100 bg-white rounded-b-2xl flex justify-between items-center text-xs text-gray-500">
           <span>SECURE VIEWER</span>
           <span>Generated by Seeding OS</span>
        </div>
      </div>
    </div>
  );
};